# Generated by Django 6.0.3 on 2026-04-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_classmonthlyfee_bus_fee_and_more'),
        ('school_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Current Academic Year for Students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_schools', to='finance.financialyear'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Current Financial Year for Staff/Payroll', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_schools', to='finance.financialyear'),
        ),
    ]
