# Generated by Django 6.0.3 on 2026-04-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0002_schoolsetting_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='current_term',
            field=models.CharField(choices=[('first', 'First Term'), ('mid', 'Mid Term'), ('third', 'Third Term'), ('final', 'Final / Annual'), ('pre', 'Pre-Board'), ('trial', 'Trial'), ('custom', 'Custom')], default='first', help_text='Current Active Academic Term', max_length=20),
        ),
    ]
