# Generated by Django 6.0.3 on 2026-04-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0003_schoolsetting_current_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsetting',
            name='current_term',
        ),
    ]
