# Generated by Django 6.0.1 on 2026-03-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_classsubject_elective_group_subject_elective_group'),
        ('students', '0004_student_photo_alter_student_alns_emis_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='elective_subjects',
            field=models.ManyToManyField(blank=True, related_name='students_enrolled', to='academics.subject'),
        ),
    ]
