# Generated by Django 6.0.1 on 2026-03-31 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_busroute'),
        ('students', '0005_student_elective_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='finance.busroute'),
        ),
    ]
