# Generated by Django 6.0.3 on 2026-04-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
