# Generated by Django 6.0.3 on 2026-04-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_schoolholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date_bs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth_bs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
