# Generated by Django 6.0.3 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_admission_date_bs_student_date_of_birth_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='symbol_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
