# Generated by Django 6.0.1 on 2026-03-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Staff Salary'), ('rent', 'Rent & Lease'), ('utilities', 'Utilities (Elec/Water)'), ('maintenance', 'Maintenance & Repairs'), ('supplies', 'Stationery & Supplies'), ('sports', 'Sports & Events'), ('other', 'Miscellaneous')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('recipient', models.CharField(help_text='Who was paid (e.g., Staff Name, Shop Name)', max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer')], default='cash', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.financialyear')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
