# Generated by Django 6.0.1 on 2026-04-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_classsubject_elective_group_subject_elective_group'),
        ('finance', '0003_busroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveSubjectFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(help_text='e.g. Computer Fee, Music Lab Fee', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_fees', to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_settings', to='academics.subject')),
            ],
            options={
                'ordering': ['class_obj__name', 'subject__name'],
                'unique_together': {('class_obj', 'subject')},
            },
        ),
    ]
