# Generated by Django 6.0.3 on 2026-04-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_electivesubjectfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('salary', 'Staff Salary'), ('rent', 'Rent & Lease'), ('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet / Phone'), ('stationery', 'Stationery & Supplies'), ('furniture', 'Furniture & Fixtures'), ('equipment', 'Equipment & Technology'), ('maintenance', 'Maintenance & Repairs'), ('sports', 'Sports & Events'), ('transport', 'Transport'), ('food', 'Food & Refreshments'), ('cleaning', 'Cleaning & Sanitation'), ('bank_charge', 'Bank Charges & Fees'), ('tax', 'Taxes & Government Fees'), ('other', 'Miscellaneous')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('paid_to', models.CharField(blank=True, help_text='Vendor, staff name, etc.', max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('bank', 'Bank Transfer')], default='cash', max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='school_finance/expenditure/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('fee_income', 'Student Fee Income'), ('government', 'Government Grant / Fund'), ('donation', 'Donation'), ('bank_interest', 'Bank Interest'), ('sale', 'Sale of Assets / Materials'), ('event', 'Event / Program Income'), ('other', 'Other Income')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('received_from', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('bank', 'Bank Deposit')], default='cash', max_length=20)),
                ('reference_no', models.CharField(blank=True, help_text='Cheque/receipt/voucher number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
