# Generated by Django 6.0.3 on 2026-04-08 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_school_income_expenditure'),
        ('students', '0009_student_admission_date_bs_student_date_of_birth_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='billing_months',
            field=models.CharField(default='1,2,3,4,5,6,7,8,9,10,11,12', help_text='Comma separated Nepali months (1-12) when this fee is charged', max_length=100),
        ),
        migrations.CreateModel(
            name='MonthlyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Nepali Month (1=Baishakh, 12=Chaitra)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_items_json', models.JSONField(default=dict, help_text='Snapshot of fee items at time of generation')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_demands', to='finance.financialyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_demands', to='students.student')),
            ],
            options={
                'ordering': ['financial_year__start_date', 'month'],
                'unique_together': {('student', 'financial_year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PreviousYearDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previous_dues', to='finance.financialyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_year_dues', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'financial_year')},
            },
        ),
    ]
