# Generated by Django 6.0.3 on 2026-04-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_classsubject_elective_group_subject_elective_group'),
        ('finance', '0007_feediscount_studentdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydemand',
            name='bus_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlydemand',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlydemand',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ClassMonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Nepali Month (1=Baishakh, 12=Chaitra)')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bus_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fees', to='academics.class')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_fees', to='finance.financialyear')),
            ],
            options={
                'ordering': ['class_obj', 'financial_year', 'month'],
                'unique_together': {('class_obj', 'financial_year', 'month')},
            },
        ),
    ]
