# Generated by Django 6.0.3 on 2026-04-08 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_monthlydemand_bus_fee_monthlydemand_other_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmonthlyfee',
            options={'ordering': ['month']},
        ),
        migrations.AlterUniqueTogether(
            name='classmonthlyfee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classmonthlyfee',
            name='structure_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fees', to='finance.classfeedetail'),
        ),
        migrations.RemoveField(
            model_name='classmonthlyfee',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='classmonthlyfee',
            name='financial_year',
        ),
    ]
