# Generated by Django 6.0.3 on 2026-04-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_classmonthlyfee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmonthlyfee',
            options={'ordering': ['structure_detail', 'month']},
        ),
        migrations.AlterField(
            model_name='classmonthlyfee',
            name='structure_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fees', to='finance.classfeedetail'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classmonthlyfee',
            unique_together={('structure_detail', 'month')},
        ),
    ]
