# Generated by Django 6.0.3 on 2026-04-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_classmonthlyfee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='end_date_bs',
            field=models.CharField(blank=True, help_text='Nepali End Date (YYYY-MM-DD)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='start_date_bs',
            field=models.CharField(blank=True, help_text='Nepali Start Date (YYYY-MM-DD)', max_length=10, null=True),
        ),
    ]
