# Generated by Django 6.0.3 on 2026-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_financialyear_end_date_bs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
