# Generated by Django 6.0.3 on 2026-04-08 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_financialyear_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeeenrollment',
            name='class_fee_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='finance.classfeedetail'),
        ),
    ]
