# Generated by Django 6.0.3 on 2026-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_studentfeeenrollment_class_fee_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmonthlyfee',
            name='bus_fee',
        ),
        migrations.RemoveField(
            model_name='classmonthlyfee',
            name='other_fee',
        ),
        migrations.RemoveField(
            model_name='classmonthlyfee',
            name='tuition_fee',
        ),
        migrations.RemoveField(
            model_name='monthlydemand',
            name='bus_fee',
        ),
        migrations.RemoveField(
            model_name='monthlydemand',
            name='other_fee',
        ),
        migrations.RemoveField(
            model_name='monthlydemand',
            name='tuition_fee',
        ),
        migrations.AlterField(
            model_name='classmonthlyfee',
            name='month',
            field=models.IntegerField(),
        ),
    ]
