# Generated by Django 6.0.3 on 2026-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain_url', models.CharField(help_text='e.g., school1.sajiloschool.com or school1', max_length=100, unique=True)),
                ('db_name', models.CharField(help_text='Database name or sqlite filename without extension', max_length=100, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
