# Generated by Django 6.0.3 on 2026-04-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/'),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
