# Generated by Django 6.0.1 on 2026-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_schooltenant_address_schooltenant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
