# Generated by Django 6.0.3 on 2026-03-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_routines', to='academics.class'),
        ),
        migrations.AlterUniqueTogether(
            name='examroutine',
            unique_together={('exam', 'subject', 'class_obj')},
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='faculty',
        ),
    ]
