# Generated by Django 6.0.3 on 2026-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examroutine_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
