# Generated by Django 6.0.3 on 2026-03-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_classsubject'),
        ('exams', '0003_subject_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examroutine',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academics.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
