# Generated by Django 6.0.1 on 2026-03-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_examroutine_subject_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='exam_date',
            field=models.CharField(max_length=10),
        ),
    ]
