# Generated by Django 6.0.1 on 2026-03-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_exam_end_date_alter_exam_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examroutine',
            name='end_time',
        ),
    ]
