# Generated by Django 6.0.1 on 2026-03-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_examroutine_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_date',
        ),
    ]
