# Generated by Django 6.0.3 on 2026-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_exam_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='has_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='practical_full_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='practical_pass_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='theory_full_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='theory_pass_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='markledger',
            name='practical_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='markledger',
            name='theory_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
