# Generated by Django 6.0.3 on 2026-04-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_classsubject_elective_group_subject_elective_group'),
        ('exams', '0009_examroutine_has_practical_and_more'),
        ('students', '0009_student_admission_date_bs_student_date_of_birth_bs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStudentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_summaries', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_summaries', to='students.student')),
            ],
            options={
                'ordering': ['student__class_name', 'student__roll_number'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
