# Generated by Django 6.0.3 on 2026-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_examstudentsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_working_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
