# Generated by Django 6.0.3 on 2026-04-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_acc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('Teaching', 'Teaching Section'), ('Account', 'Account Section'), ('Administration', 'Administration Section')], default='Teaching', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_married',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Married', max_length=15),
        ),
        migrations.AddField(
            model_name='teacher',
            name='job_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pan_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='perm_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='post',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Accountant', 'Accountant'), ('Manager', 'Manager'), ('Principal', 'Principal'), ('Staff', 'Staff')], default='Teacher', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='promoted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ssf_fund',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='temp_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='training',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StaffMonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Baisakh', 'Baisakh'), ('Jestha', 'Jestha'), ('Ashad', 'Ashad'), ('Shrawan', 'Shrawan'), ('Bhadra', 'Bhadra'), ('Ashwin', 'Ashwin'), ('Kartik', 'Kartik'), ('Mangshir', 'Mangshir'), ('Poush', 'Poush'), ('Magh', 'Magh'), ('Falgun', 'Falgun'), ('Chaitra', 'Chaitra')], max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tiffin_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dashain_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_add', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_add', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_less', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('miss_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_less', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('absent_less', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salaries', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tiffin_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dashain_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_add', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_add', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='teachers.teacher')),
            ],
        ),
    ]
