# Generated by Django 6.0.3 on 2026-04-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_payrollsettings_staffcategory_staffpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='advance_add_heading',
            field=models.CharField(default='Advance Add', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='basic_salary_heading',
            field=models.CharField(default='Basic Salary', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='dashain_bonus_heading',
            field=models.CharField(default='Dashain Bonus', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='other_allow_heading',
            field=models.CharField(default='Other Allow.', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='pf_add_heading',
            field=models.CharField(default='PF Add', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='special_allow_heading',
            field=models.CharField(default='Special Allow.', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='tiffin_allow_heading',
            field=models.CharField(default='Tiffin Allow.', max_length=50),
        ),
    ]
