# Generated by Django 6.0.3 on 2026-04-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_payrollsettings_advance_add_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsettings',
            name='advance_add_heading',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='basic_salary_heading',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='dashain_bonus_heading',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='other_allow_heading',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='pf_add_heading',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='special_allow_heading',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='tiffin_allow_heading',
        ),
        migrations.RemoveField(
            model_name='staffmonthlysalary',
            name='advance_add',
        ),
        migrations.RemoveField(
            model_name='staffmonthlysalary',
            name='dashain_bonus',
        ),
        migrations.RemoveField(
            model_name='staffmonthlysalary',
            name='other_allowance',
        ),
        migrations.RemoveField(
            model_name='staffmonthlysalary',
            name='pf_add',
        ),
        migrations.RemoveField(
            model_name='staffmonthlysalary',
            name='special_allowance',
        ),
        migrations.RemoveField(
            model_name='staffmonthlysalary',
            name='tiffin_allowance',
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='advance_add',
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='dashain_bonus',
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='other_allowance',
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='pf_add',
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='special_allowance',
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='tiffin_allowance',
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='salary_components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='staffmonthlysalary',
            name='allowances',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='staffsalarystructure',
            name='allowances',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
