# Generated by Django 6.0.3 on 2026-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_remove_payrollsettings_advance_add_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='absent_deduction_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
