# Generated by Django 6.0.3 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_payrollsettings_absent_deduction_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsettings',
            name='absent_deduction_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
