# Generated by Django 6.0.3 on 2026-03-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='full_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks',
            field=models.PositiveIntegerField(default=35),
        ),
    ]
