# Generated by Django 6.0.1 on 2026-03-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_options_subject_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
