# Generated by Django 6.0.1 on 2026-03-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subject_is_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
