# Generated by Django 6.0.1 on 2026-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_classsubject_is_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='elective_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='elective_group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
